language: go

sudo: false

go:
  - 1.8

before_install:
  - make dependencies

before_script:
  - make format
  - make vet

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)