language: go

sudo: false

go:
  - 1.6

before_install:
  - go get -t github.com/scootdev/scoot/...

before_script:
  - go fmt ./...
  - go vet $(go list ./...)

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)